# Generated by Django 3.0.2 on 2020-01-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoastBoast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roast', models.BooleanField(default=True)),
                ('content', models.CharField(max_length=280)),
                ('votes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('posttime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
