# Generated by Django 3.0.2 on 2020-01-14 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchaldatas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='level',
            new_name='mptt_level',
        ),
    ]
